# tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "leoafarias/fvm"

# tools / libraries
brew "asdf"
brew "cocoapods"
brew "fd" # Simple, fast and user-friendly alternative to find
brew "openjdk@11"
brew "stow"
brew "starship"
brew "mas" # Mac App Store command-line interface
brew "ripgrep" # Search tool like grep and The Silver Searcher
brew "tree" # Display directories as trees (with optional color/HTML output)
brew "leoafarias/fvm/fvm"
brew "postgresql@15"
brew "chezmoi"

cask "google-cloud-sdk"
cask "karabiner-elements"

# gui
cask "android-studio"
cask "cleanmymac"
cask "cleanshot"
cask "discord"
cask "docker"
cask "figma"
cask "fork"
cask "google-chrome"
cask "inkscape"
cask "krita"
cask "notion"
cask "pgadmin4"
cask "raycast"
cask "slack"
cask "visual-studio-code"
cask "zoom"

# languages
brew "go"

# fonts
cask "font-hack-nerd-font"
cask "font-ricty-diminished"

# mas
mas "Bitwarden", id: 1352778147
mas "LINE", id: 539883307
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
