tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "leoafarias/fvm"
brew "asdf"
brew "cocoapods"
brew "fd"
brew "go"
brew "mas"
brew "openjdk@11"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tree"
brew "leoafarias/fvm/fvm"
cask "affinity-designer"
cask "android-studio"
cask "cleanmymac"
cask "cleanshot"
cask "docker"
cask "figma"
cask "font-hack-nerd-font"
cask "font-ricty-diminished"
cask "fork"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "karabiner-elements"
cask "maccy"
cask "notion"
cask "slack"
cask "visual-studio-code"
cask "zoom"
mas "BetterSnapTool", id: 417375580
mas "Bitwarden", id: 1352778147
mas "Xcode", id: 497799835
