#!/bin/sh

# エラーや未定義変数への参照があれば即終了
set -eu

cd $HOME

# OSチェック
if [ "$(uname -m)" != "arm64" ] ; then
	echo "このスクリプトはAppleシリコンを搭載したMac OSでのみ動作します。"
	exit 1
fi

# 参考: https://zenn.dev/watsuyo_2/articles/734f3bf537b7ad
# Homebrewをインストールする
if [ ! -f /opt/homebrew/bin/brew ]
	then
		echo "Homebrewをインストールしています..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	else
		echo "Homebrewは既にインストールされています。"
fi

# dotfilesをクローンする
if [ ! -d $HOME/dotfiles ]
	then
		cd $HOME/.ssh
		echo "公開鍵をGitHubに登録しましたか？[y/N]"
		read answer
		case $answer in
		[Yy]* )
			;;
		* )
			echo "公開鍵をGitHubに登録してからやり直してください。"
			echo "1. ssh-keygen -t ed25519 -C YOUR_EMAIL_ADDRESS"
			echo "2. pbcopy < ~/.ssh/id_rsa.pub"
			echo "詳細は https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account を確認してください。"
			;;
		esac

		echo "dotfilesをダウンロードしています..."
		git clone git@github.com:ymgn9314/dotfiles.git
	else
		echo "dotfilesは既にダウンロードされています。"
		echo "インストールを続行しますか？[y/N]"
		read answer
		case $answer in
		[Yy]* )
			;;
		* )
			echo "インストールを中止します。"
			exit 0
			;;
		esac
fi

# Brewfileのインストール
echo "ソフトウェアやツールをインストールしています..."
brew bundle -v --file=$HOME/dotfiles/Brewfile

# 設定ファイルのシンボリックリンク設定(Stow)
stow -v $HOME/dotfiles/git $HOME/dotfiles/karabiner $HOME/dotfiles/kitty $HOME/dotfiles/zsh

# Rosetta 2のインストール
# asdf, fvmの操作でRosetta 2が必要になるため必ず先に実行すること
sh $HOME/dotfiles/sh/rosetta.sh

# システム設定
sh $HOME/dotfiles/sh/defaults.sh

# asdfインストール
sh $HOME/dotfiles/sh/asdf.sh

# fvmインストール
sh $HOME/dotfiles/sh/fvm.sh