name: "test setup"
on: [workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: actions/checkout@v3
      - name: Run setup
      - run: sh setup